//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmhLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmhKhoa
    {
        public string NmhMaKH { get; set; }
        public string NmhTenKH { get; set; }
        public Nullable<bool> NmhTrangThai { get; set; }
    }
}
