//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmhLesson09.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NmhK22CNT1Lesson09Entities : DbContext
    {
        public NmhK22CNT1Lesson09Entities()
            : base("name=NmhK22CNT1Lesson09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NmhKhoa> NmhKhoa { get; set; }
        public virtual DbSet<NmhSinhVien> NmhSinhVien { get; set; }
    }
}
