//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmhLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NmhSinhVien
    {
        public string NmhMaSV { get; set; }
        public string NmhHoSV { get; set; }
        public string NmhTenSV { get; set; }
        public Nullable<System.DateTime> NmhNgaySinh { get; set; }
        public Nullable<bool> NmhPhai { get; set; }
        public string NmhPhone { get; set; }
        public string NmhEmail { get; set; }
        public string NmhMaKH { get; set; }
    }
}
