//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmhCNT1K22Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenMinhHiep_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenMinhHiep_TACGIA()
        {
            this.NguyenMinhHiep_SACH = new HashSet<NguyenMinhHiep_SACH>();
        }
    
        public int NguyenMinhHiep_MaTG { get; set; }
        public string NguyenMinhHiep_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguyenMinhHiep_SACH> NguyenMinhHiep_SACH { get; set; }
    }
}
