//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NmhCNT1K22Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenMinhHiep_SACH
    {
        public int NguyenMinhHiep_MaSach { get; set; }
        public string NguyenMinhHiep_TenSach { get; set; }
        public Nullable<int> NguyenMinhHiep_SoTrang { get; set; }
        public Nullable<int> NguyenMinhHiep_NamXB { get; set; }
        public Nullable<int> NguyenMinhHiep_MaTG { get; set; }
        public Nullable<bool> NguyenMinhHiep_TrangThai { get; set; }
    
        public virtual NguyenMinhHiep_TACGIA NguyenMinhHiep_TACGIA { get; set; }
    }
}
